# Generated by Django 2.2 on 2019-05-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(help_text='이름', max_length=32, unique=True),
        ),
    ]
