# Generated by Django 2.2 on 2019-05-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20190502_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(help_text='이름', max_length=32),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.CharField(blank=True, choices=[('READY', '준비'), ('PLAY', '진행중'), ('END', '종료')], default='READY', help_text='상태', max_length=8),
        ),
    ]
