# Generated by Django 2.2 on 2019-05-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20190504_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersession',
            name='state',
            field=models.CharField(blank=True, choices=[('JOINED', '참여한'), ('EXITED', '퇴장한')], default='JOINED', help_text='참여 상태', max_length=8),
        ),
    ]
