# Generated by Django 2.2 on 2019-05-05 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('session', '0005_auto_20190505_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card',
            field=models.ForeignKey(default=0, help_text='카드', on_delete=django.db.models.deletion.CASCADE, to='game.CardClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='카드 뭉치 속에서 순서, 0부터 가장 위', null=True),
        ),
    ]
