# Generated by Django 2.2 on 2019-05-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20190505_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='face',
            field=models.CharField(blank=True, choices=[('FRONT', '앞면'), ('BACK', '뒷면')], default='FRONT', help_text='보드 위 보이는 면', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='location',
            field=models.CharField(choices=[('DECK', '덱'), ('HAND', '핸드'), ('BOARD', '보드')], default='DECK', help_text='카드의 위치', max_length=8),
        ),
        migrations.AlterField(
            model_name='card',
            name='pos_z',
            field=models.PositiveSmallIntegerField(blank=True, help_text='보드 위 z 좌표, 보이는 카드의 값이 0이 되도록 한다.', null=True),
        ),
    ]
