# Generated by Django 2.2 on 2019-05-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20190505_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(help_text='보드 위 x 좌표')),
                ('y', models.PositiveSmallIntegerField(help_text='보드 위 y 좌표')),
            ],
        ),
    ]
