# Generated by Django 2.2 on 2019-05-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='card',
            name='pos_y',
        ),
        migrations.AddField(
            model_name='card',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Board'),
        ),
    ]
