# Generated by Django 2.2 on 2019-05-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_auto_20190508_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='session',
            field=models.ForeignKey(default=1, help_text='세션', on_delete=django.db.models.deletion.CASCADE, to='session.Session'),
            preserve_default=False,
        ),
    ]
