# Generated by Django 2.2 on 2019-05-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_board_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pos_z',
            field=models.PositiveSmallIntegerField(blank=True, help_text='보드 위 z 좌표', null=True),
        ),
    ]
