# Generated by Django 2.2 on 2019-05-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_front', models.CharField(default='#000000', help_text='앞면 색', max_length=8)),
                ('color_back', models.CharField(default='#ffffff', help_text='뒷면 색', max_length=8)),
                ('count', models.PositiveSmallIntegerField(default=10, help_text='카드 수')),
            ],
        ),
    ]
